import 'package:flutter/material.dart';

class AppTextColors {
  static final List<Color> availableColors = [
    Colors.white,
    Colors.white60,
    Colors.white70,
    Colors.white54,
    Colors.white38,
    Colors.grey,
    Colors.grey.shade300,
    Colors.grey.shade400,
    Colors.grey.shade500,
    Colors.grey.shade600,
    Colors.grey.shade700,
    Colors.grey.shade800,
    Colors.grey.shade900,
    Colors.black,
    Colors.red,
    Colors.redAccent,
    Colors.pink,
    Colors.pinkAccent,
    Colors.purple,
    Colors.purpleAccent,
    Colors.deepPurple,
    Colors.deepPurpleAccent,
    Colors.indigo,
    Colors.indigoAccent,
    Colors.blue,
    Colors.blueAccent,
    Colors.lightBlue,
    Colors.lightBlueAccent,
    Colors.cyan,
    Colors.cyanAccent,
    Colors.teal,
    Colors.tealAccent,
    Colors.green,
    Colors.greenAccent,
    Colors.lightGreen,
    Colors.lightGreenAccent,
    Colors.lime,
    Colors.limeAccent,
    Colors.yellow,
    Colors.yellowAccent,
    Colors.amber,
    Colors.amberAccent,
    Colors.orange,
    Colors.orangeAccent,
    Colors.deepOrange,
    Colors.deepOrangeAccent,
    Colors.brown,
  ];

  static const List<String> colorNames = [
    'White',
    'White 60%',
    'White 70%',
    'White 54%',
    'White 38%',
    'Grey',
    'Light Grey',
    'Grey 400',
    'Grey 500',
    'Grey 600',
    'Grey 700',
    'Grey 800',
    'Grey 900',
    'Black',
    'Red',
    'Red Accent',
    'Pink',
    'Pink Accent',
    'Purple',
    'Purple Accent',
    'Deep Purple',
    'Deep Purple Accent',
    'Indigo',
    'Indigo Accent',
    'Blue',
    'Blue Accent',
    'Light Blue',
    'Light Blue Accent',
    'Cyan',
    'Cyan Accent',
    'Teal',
    'Teal Accent',
    'Green',
    'Green Accent',
    'Light Green',
    'Light Green Accent',
    'Lime',
    'Lime Accent',
    'Yellow',
    'Yellow Accent',
    'Amber',
    'Amber Accent',
    'Orange',
    'Orange Accent',
    'Deep Orange',
    'Deep Orange Accent',
    'Brown',
  ];
}

